// <auto-generated />
using Ecommerce_BE.Data.Domains;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce_BE.Migrations
{
    [DbContext(typeof(EcommerceContext))]
    [Migration("20230909174240_initCreate")]
    partial class initCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ecommerce_BE.Data.Domains.IngerProduct", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IngerdientID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("SumCost")
                        .HasColumnType("double");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.HasIndex("IngerdientID");

                    b.HasIndex("ProductID");

                    b.ToTable("detailProducts");
                });

            modelBuilder.Entity("Ecommerce_BE.Data.Domains.Ingerdient", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("ImportPrice")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("PricePerGram")
                        .HasColumnType("double");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("ingerdients");
                });

            modelBuilder.Entity("Ecommerce_BE.Data.Domains.Product", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Cost")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Ecommerce_BE.Data.Domains.IngerProduct", b =>
                {
                    b.HasOne("Ecommerce_BE.Data.Domains.Ingerdient", null)
                        .WithMany()
                        .HasForeignKey("IngerdientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce_BE.Data.Domains.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
